### ISSUE TITLE
Update workflow to install Lua & LuaRocks via apt-get

### ISSUE THREAD

**Issue by kaklakariada** [exasol/remotelog-lua#22]
As the current GitHub actions runner uses Ubuntu 20.04 which does not contain Lua 5.4 we need to use a custom [GH Action](https://github.com/marketplace/actions/install-lua-luajit), see https://github.com/exasol/remotelog-lua/pull/21.

Once the runner is updated to Ubuntu 22.04 we can use the following step to install Lua:

```yml
      - name: "Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get -y install lua${{ matrix.lua_version }} liblua${{ matrix.lua_version }} lua-any luarocks
```
